theme = "dark"

[themes.dark]
current_line_bg = "#464646"
syntax_keyword = "#569CD6"
syntax_string = "#6A9955"
syntax_comment = "#6A9955"
syntax_function = "#DCDCAA"
syntax_type = "#4EC9B0"
syntax_number = "#B5CEA8"

# keymap_debug = true

[keymap.command]
"<M-Backspace>" = "delete_word"
"<M-Left>" = "word_left"
"<M-Right>" = "word_right"
"<D-Left>" = "line_start"
"<D-Right>" = "line_end"
